# Generated by Django 4.0.6 on 2022-07-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="unit_price",
            new_name="price",
        ),
    ]
